<#macro display>
    <div class="footer">
        <span class="pull-right">
            <span>(c) 2025 Dick Kouwenhoven    Generated by </span>
            <a class="footer--link footer--link_external" href="https://github.com/Kotlin/dokka">
                <span>dokka</span>               
            </a>            
        </span>
    </div> 
</#macro>
